name: ligo

channels:
  - defaults
  
dependencies:
  - python=2.7
  
  - ipykernel=4.8
  - decorator=4.4
  - matplotlib=2.2
  - scipy = 1.2
  - numpy= 1.16
  - h5py=2.10
  - json=18.2
  - libgcc_mutex=0.1                 
  - _openmp_mutex             4.5                       
  - backports                 1.0                        
  - backports.functools_lru_cache 1.6                  
  - backports.shutil_get_terminal_size 1.0                   
  - backports_abc             0.5                       
  - ca-certificates           2021.10         
  - certifi                   2019.11      
  - configparser              3.7          
  - entrypoints               0.3             
  - enum34                    1.1
  - futures                   3.3
  - ipython                   5.8
  - ipython_genutils          0.2
  - jupyter_client            5.3
  - jupyter_core              4.6
  - ld_impl_linux-64          2.36
  - libffi                    3.2
  - libgcc-ng                 11.2
  - libgomp                   11.2
  - libsodium                 1.0
  - libstdcxx-ng              11.2
  - libzlib                   1.2
  - ncurses                   6.3                 
  - openssl                   1.1
  - pathlib2                  2.3
  - pexpect                   4.8
  - pickleshare               0.7
  - pip                       20.1
  - prompt_toolkit            1.0
  - ptyprocess                0.7
  - pygments                  2.5
  - python-dateutil           2.8
  - python_abi                2.7   
  - pyzmq                     19.0
  - readline                  8.1    
  - scandir                   1.10
  - setuptools                44.0
  - simplegeneric             0.8
  - singledispatch            3.6
  - six                       1.16
  - sqlite                    3.38
  - tk                        8.6
  - tornado                   5.1
  - traitlets                 4.3
  - wcwidth                   0.2
  - wheel                     0.37
  - zeromq                    4.3
  - zlib                      1.2
  
 # prefix: /home/jovyan/envs/ligo
 
